### ISSUE TITLE
using Flat.Physics error

### ISSUE THREAD

**Issue by NightfoxGames** [twobitcoder101/Flat#4]
soo, i want to folow the tutorial about creating a physics engine, i download the Flat Library. 

it all goes well untill i stumble in a error saying `Flat.Physics is not found` in the `FlatCircle` script. Can you help me

**Comment by twobitcoder101** [comment]
It should be fixed now. Thanks for letting me know! 😀

**Comment by NightfoxGames** [comment]
thanks a lot
